### ISSUE TITLE
Does FSDP support: the world has 16 GPUs, but parameters are sharded on 8 GPUs.

### ISSUE THREAD

**Issue by amsword** [facebookresearch/fairscale#1039]
if so, is there any example?

**Comment by min-xu-ai** [comment]
You mean having 2 separate groups each with 8 GPUs for sharding? Yes, it is not very well testing but you can supply your own process_groups on each rank so that [0-7] and [8-15] can be in their own groups. In that way, the all-gather will happen within the groups and memory saving from sharding will not be as good as 16-gpus groups. But this can be useful if within the group the networking b/w is much higher.

Be careful about supplying the process groups for the reduction for the gradients as well. It is important to have a separate group for them for better backward performance. Therefore, you would need 4 process groups if you want 8 gpus in each group for total of 16 gpus.

I don't think we have an example unfortunately.

**Comment by amsword** [comment]
> 

Thanks for the comment. The scenario you are describing is the one I was thinking of. One question is that after backward, is there an extra procedure to sync the gradient between the two process groups? It seems like the 4 process groups you mentioned is about this issue? Why is it 4 process groups?

**Comment by min-xu-ai** [comment]
check the init function of FSDP. It takes 2 process groups optionally. Therefore, there will be 4 total of you group 16 gpus into 2 groups.
