### ISSUE TITLE
Memory reduction in the EMA mode

### ISSUE THREAD

**Issue by voidrank** [facebookresearch/fairscale#1061]
Hi,

We are using FairScale to reduce memory to scale up our models. However, when we are using FairScale to do EMA (exponantial moving average) as described as follows:

```
class ExampleNet(nn.Module):
    ...

    @torch.no_grad()
    def update(self, student):
        for param_student, param_teacher in zip(student.parameters(), self.parameters()):
            param_teacher.data = param_teacher.data * self.momentum + param_student.data * (1 - self.momentum)
```

EMA network doesn't need ```backward``` or ```apply activation```. You can regard it as `eval` nn.module, but its parameters need to be updated manually after each step.

This network costs significant memory compared to the classic ```nn.Module```. I guess FairScale doesn't optimize the memory here.

Can you help me out?

Thanks,

Shiyi

**Comment by min-xu-ai** [comment]
We actually do use FSDP with ema models like data2vec. It is possible to wrap the EMA model and let FSDP shard it and reduce memory. You do need to have deeper knowledge about FSDP to effectively use it. It is not an oneline change and you may run into issues that requires you to wrap model in specific ways etc.

Can you share more details of what you are trying to do and what issues you have run into already?

**Comment by voidrank** [comment]
Hi @min-xu-ai ,

Thanks for the prompt responses. I will look into FSDP and learn to use it. Could you give the link to data2vec that incorporates FSDP?

I'm currently developing a new model which needs an EMA teacher to train the student net during training. I have done all the coding with pytorch_lightning and managed to use FSDP to reduce the memory consumption of the student net. However, I failed to use FSDP to reduce the memory of the teacher net. That's the reason I'm here to ask.

Thanks!

**Comment by min-xu-ai** [comment]
I am not sure all the code is public but data2vec and ema code should be in fairseq and it uses FSDP there. 

Since you are using lighting, you might need to check with them or use FSDP directly

**Comment by min-xu-ai** [comment]
Here is some high level things about how to do EMA with FSDP. At least this represents one way:

* put ema model in a class that's not nn.Module

```
class Foo:
   def __init__(self, ema_model):
     self.model = ema_model
```

* Then, put this model inside the main model
```
...
  self.ema = Foo(ema_model)
...
```
* this way, when the main model is wrapped, the ema model is not automatically wrapped by FSDP.
* then, you want to wrap your main model and ema model with FSDP separately:
```
model.ema.model = FSDP(model.ema.model)
model = FSDP(model)
```
* After this, you can save memory in both model

the reason we put ema_model inside Foo class is to make sure it doesn't get automatically wrapped or in anyway all-gathered automatically in the main model's forward & backward passes.

Then, inside the main model forward or other places, you can call into the foo.ema_model and trigger FSDP's forward pass for the ema model as you needed.

You do need to understand the internals of FSDP a bit to effectively wrap your model so that when you are copying the parameters from & to the ema model you can make sure you are doing the right thing, either with the sharded parameters or the full parameters (with the `summon_full_params` context of the FSDP wrapper.

We now have a working and tested code for something like this, so I am pretty confident this route works. I don't have time to provide exact examples unfortunately. Feel free to ask additional questions if you run into any specific issues.

I will close this for and please reopen if needed.

**Comment by VictorChen2012** [comment]
> Here is some high level things about how to do EMA with FSDP. At least this represents one way:
> 
> * put ema model in a class that's not nn.Module
> 
> ```
> class Foo:
>    def __init__(self, ema_model):
>      self.model = ema_model
> ```
> 
> * Then, put this model inside the main model
> 
> ```
> ...
>   self.ema = Foo(ema_model)
> ...
> ```
> 
> * this way, when the main model is wrapped, the ema model is not automatically wrapped by FSDP.
> * then, you want to wrap your main model and ema model with FSDP separately:
> 
> ```
> model.ema.model = FSDP(model.ema.model)
> model = FSDP(model)
> ```
> 
> * After this, you can save memory in both model
> 
> the reason we put ema_model inside Foo class is to make sure it doesn't get automatically wrapped or in anyway all-gathered automatically in the main model's forward & backward passes.
> 
> Then, inside the main model forward or other places, you can call into the foo.ema_model and trigger FSDP's forward pass for the ema model as you needed.
> 
> You do need to understand the internals of FSDP a bit to effectively wrap your model so that when you are copying the parameters from & to the ema model you can make sure you are doing the right thing, either with the sharded parameters or the full parameters (with the `summon_full_params` context of the FSDP wrapper.
> 
> We now have a working and tested code for something like this, so I am pretty confident this route works. I don't have time to provide exact examples unfortunately. Feel free to ask additional questions if you run into any specific issues.
> 
> I will close this for and please reopen if needed.

Hi, thanks for the hints above.

In my using case, I also try to fsdp on ema module. However, I cannot do ema.model.summon_full_params in the main model's forward function and raise states error like "expect to be in states [training_state.IDLE] but current state in [training_state.FORWARD]". This error is as expected as mentioned in the API document that cannot summon_full_params under forward state. 

So, just wondering if you have test code in the main branch and then I can learn how to further adapt my codes. Thanks!

**Comment by min-xu-ai** [comment]
Unfortunately, I don't have the access to the code I wrote anymore. Even if I do, I probably can't share it.

For the error you are facing, it is probably because your ema model end up in the forward state automatically for some reason. You want to make sure it is not part of the main model when the main model's forward is called. That way, inside the main model's forward, you will be able to call summon_full_params on the ema model.
