### ISSUE TITLE
All parameters cannot be shared amongst 2 different FSDP modules

### ISSUE THREAD

**Issue by sarthakgarg** [facebookresearch/fairscale#1117]
Hi, reading through https://github.com/facebookresearch/fairscale/blob/5b38de380e4407c2ef02f357ebc640f53470ea24/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L540, there seems to be some constraints if we want to share parameters between different FSDP modules:
1. Cannot use flatten on the FSDP modules
2. FSDP modules need to have atleast some unshared parameters.

Was wondering the need for imposing constraint 2? I want to share weights of encoder and decoder layers in a transformer model, but seems like I cannot share the whole layer?

Any leads on how to approach when all parameters need to be shared?
Thanks!

**Comment by min-xu-ai** [comment]
Thanks for the question. Yeah, the reason is due to backward pass hook firing. FSDP code is written so that it assumes every FSDP instance's backward hook needs to fire in certain order. If an instance only have shared param, it means that the backward hook may not fire on that instance. I think some needed bookkeeping might not be done as a result. Hence there is the assert.

> Any leads on how to approach when all parameters need to be shared?

You can check the MEVO code and some unit test in the tests dir to see if there are any hints. It is been a while since I worked on the shared params feature here. On top of my head, I would say try to add a dummy param that is not shared and make sure some how that param is plugged into the forward pass (so it is not an unused param). The param could be a single element tensor. I think there was a dummy param used in the mevo code somewhere. let me know if you can't find it.
