### ISSUE TITLE
Why assuming single node environment if world_size<=8 for ShardedDataParallel?

### ISSUE THREAD

**Issue by kamo-naoyuki** [facebookresearch/fairscale#395]
## ❓ Questions and Help

Thank you for sharing this project. Really useful.

I tried ShardedDataParallel with 1gpus x 2nodes, i.e. world_size=2, but I met the following.

https://github.com/facebookresearch/fairscale/blob/47042917536dfe3026543ccebd789ef3b1441ba1/fairscale/nn/data_parallel/sharded_ddp.py#L156-L157

Why do you assume single node environment if world_size<=8? Is it impossible if world_size<=8 with multiple nodes?

**Comment by blefaudeux** [comment]
Hi Naoyuki, good question !
In that case, "nodes" means server, meaning that you typically have up to 8 GPUs on a single node (for instance nvidia DGX), it does not mean world size (world size = gpu per node x nodes). You can have 8 GPUs over two nodes, and in that case this heuristic will not be optimal, I was planning to expose it in an upcoming PR actually, in the FB ecosystem it's not really typical.

Now, why do we take this into account to begin with ? The communications inside a node are typically very fast, nvlink or pcie, while having to go outside of a node is typically slow. The buckets here are used to group small parameters together, they diminish the latency cost but they have a memory cost (could be improved in the future). So it's a tradeoff, and an initial safe bet was to assume that 8 gpus or less was a single node, so that the buckets would not help.

In your case if you're testing with 2 gpus I'm guessing that they are on a single machine, so you probably don't need buckets to efficiently reduce the parameters :) I hope that helps

**Comment by kamo-naoyuki** [comment]
Thank you for quick.  Sorry, my question is unclear.

I mean node is sever, so I want to say 1gpus x 2machine, really.

Not always each machine has 8gpus, though I agree it is popular setup. I think this action is not necessary because user can set reduce_buffer_size=0 by themselves if it is a single node. Why automatically change this value?

**Comment by blefaudeux** [comment]
> Thank you for quick. Sorry, my question is unclear.
> 
> I mean node is sever, so I want to say 1gpus x 2machine, really.
> 
> Not always each machine has 8gpus, though I agree it is popular setup. I think this action is not necessary because user can set reduce_buffer_size=0 by themselves if it is a single node. Why automatically change this value?

most people do not touch this value, so the idea was to try to have sane defaults. I'll put up a PR today to expose this toggle properly
