### ISSUE TITLE
[FSDP] Question about getting model state dict

### ISSUE THREAD

**Issue by shuyingsunshine21** [facebookresearch/fairscale#658]
## ❓ Questions and Help

When we collect `state_dict` of FSDP, we `summon_full_params` and do post-processing.

However, I found that when we do post processing, we have
```
state_dict[key] = state_dict[key].clone()
```
does it mean we double the memory for the model states? For large model, it would cause CUDA OOM.

What is the suggested workaround?

cc @min-xu-ai , @sshleifer

**Comment by shuyingsunshine21** [comment]
BTW, tried with using `state_dict_device=torch.device("cpu")`, then it would cause CPU OOM for multi-gpus.

**Comment by shuyingsunshine21** [comment]
Note that when we setup the model, it was originally fit into 1 GPU memory, and then we do the sharding. So I expect that when we summon the full parameters, it would not OOM.

Another related issue is: at the end of training, in lightning, we tried to teardown, by moving `LightningModule` to CPU and cleanup CUDA memory, but FSDP module would call `module.apply(__update_properties(device=torch.device('cpu')))`, which will again hit: `summon_full_params` (https://fburl.com/k43paanc) and CUDA OOM.  For this, wonder in this scenario, is it expected to summon full parameters? cc @SeanNaren, @ananthsub

**Comment by sshleifer** [comment]
This sounds like a bug that I haven't experienced before, so without a self-contained, reproducible example I can only speculate:
+ With `state_dict_device='cpu'` CPU OOM is certainly not desired behavior. 
+ I wonder what happens if we remove that `.clone` line.
+ To move forward, I suggest editing [this file](https://github.com/sshleifer/fairscale/blob/1204c7cf54ec301d46a0d3f3fd703da6b306f8f5/tests/nn/data_parallel/test_fsdp_summon_full_params.py) on a branch in a way that demonstrates where too much memory is being consumed. Or otherwise providing a self-contained, reproducible example.

**Comment by shuyingsunshine21** [comment]
Thanks @sshleifer , @min-xu-ai , I think we figured out the root cause for OOM, not FSDP problem

see https://github.com/PyTorchLightning/pytorch-lightning/pull/6152#discussion_r629087663

**Comment by min-xu-ai** [comment]
I am so glad!
