### ISSUE TITLE
FSDP state_dict returned data type when using mixed precision

### ISSUE THREAD

**Issue by epwalsh** [facebookresearch/fairscale#704]
The docstring for `FSDP.state_dict()` says that returned parameters will be in FP32: https://github.com/facebookresearch/fairscale/blob/b84b9146aca8fd575622462c1b311243e40b115c/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L647-L648.

But this is not the case when `mixed_precision=True`. So what's the best way to get the FP32 parameters when using mixed precision?

**Comment by min-xu-ai** [comment]
That's interesting. It should be full precision since we use summon_full_params with this parameter here:

https://github.com/facebookresearch/fairscale/blob/b84b9146aca8fd575622462c1b311243e40b115c/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L824

but maybe we don't have a unit test for it and it got broken. Can you double check you indeed not getting full precision params?

**Comment by epwalsh** [comment]
I was able to narrow down the issue. Apparently it's just buffers in the state dict that will be in half precision.

**Comment by min-xu-ai** [comment]
That’s great! Please share more details of what you found if you can. It can help others in the future who run into the same issue and help us improve the code to avoid this if possible.

**Comment by epwalsh** [comment]
I modified a test to show the failure here: https://github.com/facebookresearch/fairscale/pull/705
