### ISSUE TITLE
fairscale checkpointing_wrapper no effect on Memory

### ISSUE THREAD

**Issue by tobiascz** [facebookresearch/fairscale#766]
## 🐛 Bug

I tried the checkpointing feature of fairscale on an example with an RNN (GRU) and noticed that the checkpointing_wrapper has no effect on the VRAM for the GRU part.

## To Reproduce
https://gist.github.com/tobiascz/0cbb81abb98b1d094c17459b81ba8059

I used Weights and Biases here to visualize the GPU load but you can just comment that part if you dont want to install it and check manually with nvidia-smi

1. change the checkpointing_GRU to 1 
2. Run training and note VRAM usage
3. change the checkpointing_GRU to 0
4. Run training and compare with 2.

## Expected behavior

I was hoping to see a reduced memory utilization.

**Comment by min-xu-ai** [comment]
@tobiascz, thanks a lot for providing a repo. I see some issues with the repo:

* it has ` "batch_size": 1,`, which means the activation is very small.
* it checkpoints only small layers like Linear(128,32), the tensor dimension is small

checkpoint works by wrapping a layer with a lot of intermediate activations. For example:

```
def forward(self, x):
   x = self.linear1(x) # linear1.weight.shape == (128, 1024) 
   x = self.linear2(x) # linear2.weight.shape == (1024, 128)
   return x
```

For this layer, if you checkpoint it, the activation memory will be reduced since only the input (shape=(batch size, 128)) will be saved and the intermediate activation (shape=(batch size, 1024)) won't be saved during the forward and will instead be recomputed during the backward.

Therefore, can you re-examine your model to see if you can 1. try much bigger batch size and 2. checkpoint a layer with large intermediate activation?

Thanks!

Please reopen if there are more questions.
