### ISSUE TITLE
OSS detected that the parameter changed devices, re-allocating buffers 

### ISSUE THREAD

**Issue by gongbudaizhe** [facebookresearch/fairscale#781]
## ❓ Questions and Help
For each iteration, I get this message "OSS detected that the parameter changed devices, re-allocating buffers ". Is this normal? if not, what should be done?

**Comment by blefaudeux** [comment]
@gongbudaizhe would you happen to move your model to and from GPU at each iteration, or change the compute graph (make parameters trainable and no-trainable) ? The message should be limited to these cases, if not this is a bug and I would love more information to repro ! 

To give some insight, OSS has to change the way the parameters are stored, for efficiency purposes, and moving the model to cpu and back breaks that.

**Comment by gongbudaizhe** [comment]
Thanks for your prompt reply. I am not aware of any operations that move model to and from GPU, or change the compute graph. 

The model used is MoCO (don't worry, the code below is concise).  Do you have any clue?

https://github.com/facebookresearch/moco/blob/master/moco/builder.py

**Comment by blefaudeux** [comment]
Ah, I know MoCo, that's a good link ! 
So that's probably unrelated though, I'm guessing that the model is moved to GPU *after* the wrap of the optimizer ? If you wrap the optimizer last (after the model is moved to GPU), then the error should go away and the training will speed up a fair bit. I'll update the code to make it easier though, I get that this can be a hindrance, one sec

**Comment by gongbudaizhe** [comment]
Exactly! Thank you!
