### ISSUE TITLE
Help, a question about activation moving in offload.py.

### ISSUE THREAD

**Issue by swordfate** [facebookresearch/fairscale#947]
After I comment out the following line code, then run the `offload.py` code under `fairscale/benchmarks/experimental`, the code can run normally. (`python3 offload.py --debug --use_synthetic_data` )
https://github.com/facebookresearch/fairscale/blob/9f347f373e32ee5cad11a40b70b8e28a74b5e2d4/fairscale/experimental/nn/offload.py#L368

My question is, **why the backward propagation works even if activations are not moved into GPU?**

**Comment by flying-x** [comment]
@anj-s

**Comment by anj-s** [comment]
@swordfate From the other issue it looks like there is a reference to the activations that are present on the GPU which means GPU memory does not decrease nor do you need to move activations back to the GPU. I've marked the other issue as a bug and something we need to look into. Closing this issue since it is tackling the same problem.
